import http from 'node:http';
const port=Number(process.env.PORT||3000);
const html=String.raw`<!doctype html><html lang="th"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>TikTok 5 ช่อง</title><style>
*{box-sizing:border-box}body{margin:0;background:#f3f6fb;color:#14223c;font:15px system-ui,Tahoma,sans-serif}header{background:#14213d;color:white;padding:22px}header h1{margin:0;font-size:23px}main{max-width:1100px;margin:auto;padding:16px}.muted{color:#65758c;font-size:13px}nav{display:flex;gap:8px;overflow:auto;margin:16px 0}button{border:1px solid #dce3ef;border-radius:9px;background:white;padding:10px 13px;cursor:pointer;white-space:nowrap}button.active,button.primary{background:#1766ed;color:white;border-color:#1766ed}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.card,.panel{background:white;border:1px solid #e0e6f0;border-radius:12px;padding:15px;margin-bottom:14px}.card b{display:block;font-size:26px;margin-top:7px}h2{font-size:18px;margin:0 0 13px}table{border-collapse:collapse;width:100%;min-width:620px}td,th{padding:10px;text-align:left;border-bottom:1px solid #e7edf4;font-size:13px}th{background:#f5f8fc}.scroll{overflow:auto}input,select{width:100%;padding:9px;border:1px solid #d4dce8;border-radius:8px;font:inherit}input[type=checkbox]{width:auto}.form{display:grid;grid-template-columns:repeat(auto-fit,minmax(140px,1fr));gap:10px;align-items:end}.note{background:#fff5df;padding:12px;border-radius:9px;margin-bottom:14px;color:#78561c}.tag{color:#155cd0;background:#e9f1ff;border-radius:6px;padding:4px 8px}label{font-size:12px;color:#53647d} @media(max-width:500px){.cards{grid-template-columns:repeat(2,1fr)}header h1{font-size:19px}}
</style></head><body><header><h1>📊 TikTok 5 Channels</h1><div>Dashboard ปั้นช่อง 30 วัน · พนักงาน 2 คน</div></header><main><div class="note">เวอร์ชันนี้เก็บข้อมูลในเบราว์เซอร์แต่ละเครื่อง ยังไม่ซิงก์ข้ามอุปกรณ์</div><div class="cards"><div class="card">ช่อง<b>5</b></div><div class="card">พนักงาน<b>2</b></div><div class="card">งานสำเร็จ<b id="doneCount">0/30</b></div></div><nav id="nav"><button data-tab="plan">แผน 30 วัน</button><button data-tab="staff">ตารางพนักงาน</button><button data-tab="channels">บันทึก 5 ช่อง</button><button data-tab="live">เทส LIVE</button><button data-tab="report">รายงาน</button></nav><section id="content"></section></main><script>
const phases=d=>d<=3?'ปั้นช่องและลงคลิป':d===4?'ทดลอง LIVE จริง':d<=7?'รีรันเทส LIVE และคลิป':d<=14?'เพิ่มคลิปและเทสสินค้า':d<=21?'ทดลอง LIVE ขายสินค้า':'ขยายช่องที่มีออเดอร์';
const tasks=d=>d<=3?'ลงคลิป 1–3 คลิปต่อช่อง ดูฟีด ตอบคอมเมนต์':d===4?'เทส LIVE จริง ตรวจคนดูและจดผล':d<=7?'วิเคราะห์ LIVE ที่ไม่วิ่ง ปรับ Hook และทดลองใหม่':d<=14?'ผลิตคลิปตามสินค้า ทดสอบมุมขายและยอดคลิก':d<=21?'ทดลอง LIVE ขายสินค้า บันทึกออเดอร์และค่าคอม':'ขยายคลิปที่ขายได้ รีรันเทสช่องที่ยังไม่วิ่ง';
const times=['09:00–09:30','09:30–10:30','10:30–12:00','12:00–13:00','13:00–14:30','14:30–15:30','15:30–17:00','17:00–18:00'];
const staffA=['เลือกสินค้าและเขียน Hook','ถ่ายคลิปสินค้า','ตัดต่อคลิป','พัก','ผลิตคลิปชุดสอง','รีรันเทส Hook','ผลิตคลิปสำรอง','เตรียมงานพรุ่งนี้'];
const staffB=['ตรวจผล 5 ช่อง','ดูฟีดและตอบคอมเมนต์','ช่วยผลิตคลิป','พัก','ลงคลิปและจัดคิว','ตรวจผล / เทส LIVE','ลงคลิปและช่วยผลิต','สรุป Excel และยอดขาย'];
let state;try{state=JSON.parse(localStorage.getItem('tt5-state')||'{}')}catch{state={}};state.done??={};state.logs??=[];state.live??=[];let tab='plan';
const $=id=>document.getElementById(id),escapeHtml=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function save(){localStorage.setItem('tt5-state',JSON.stringify(state));$('doneCount').textContent=Object.values(state.done).filter(Boolean).length+'/30'}
function table(head,rows){return '<div class="scroll"><table><thead><tr>'+head.map(x=>'<th>'+x+'</th>').join('')+'</tr></thead><tbody>'+rows.map(row=>'<tr>'+row.map(x=>'<td>'+x+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>'}
function render(){document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));let h='';
if(tab==='plan'){h='<div class="panel"><h2>แผนปฏิบัติงานวันที่ 1–30</h2>'+table(['เสร็จ','วัน','ช่วงงาน','ภารกิจ'],Array.from({length:30},(_,i)=>{let d=i+1;return ['<input type="checkbox" data-day="'+d+'" '+(state.done[d]?'checked':'')+'>',d,'<span class="tag">'+phases(d)+'</span>',tasks(d)]}))+'</div>'}
if(tab==='staff'){let d=Number(state.workday||1);h='<div class="panel"><h2>เลือกวันทำงาน</h2><select id="workday">'+Array.from({length:30},(_,i)=>'<option value="'+(i+1)+'" '+(d===i+1?'selected':'')+'>วันที่ '+(i+1)+' — '+phases(i+1)+'</option>').join('')+'</select><p><b>ภารกิจวันนี้:</b> '+tasks(d)+'</p><p class="muted">วันที่ 4 ให้พนักงาน A และ B ร่วมกันเทส LIVE จริง โดยลดเวลาผลิตคลิปตามความจำเป็น</p></div><div class="panel"><h2>ตารางเวลา 8 ชั่วโมง</h2>'+table(['เวลา','พนักงาน A','พนักงาน B'],times.map((t,i)=>[t,staffA[i],d===4&&i===5?'ร่วมเทส LIVE และบันทึกผล':staffB[i]]))+'</div>'}
if(tab==='channels'){h='<div class="panel"><h2>บันทึกผลรายช่อง</h2><form id="logForm" class="form"><div><label>วันที่</label><input name="date" type="date" required></div><div><label>ช่อง</label><select name="channel">'+[1,2,3,4,5].map(n=>'<option>ช่อง '+n+'</option>').join('')+'</select></div>'+['clips','views','orders','commission','ads'].map((n,i)=>'<div><label>'+['คลิป','ยอดวิว','ออเดอร์','ค่าคอม','ค่าโฆษณา'][i]+'</label><input type="number" min="0" step="'+(i>2?'0.01':'1')+'" name="'+n+'" value="0"></div>').join('')+'<button class="primary">บันทึก</button></form></div><div class="panel"><h2>ประวัติ</h2>'+table(['วันที่','ช่อง','คลิป','วิว','ออเดอร์','ค่าคอม','โฆษณา'],state.logs.slice().reverse().map(x=>['date','channel','clips','views','orders','commission','ads'].map(k=>escapeHtml(x[k]))))+'</div>'}
if(tab==='live'){h='<div class="panel"><h2>ทดลอง LIVE จริง / รีรันเทส</h2><form id="liveForm" class="form"><div><label>วันที่</label><input type="date" name="date" required></div><div><label>ช่อง</label><select name="channel">'+[1,2,3,4,5].map(n=>'<option>ช่อง '+n+'</option>').join('')+'</select></div><div><label>ประเภท</label><select name="type"><option>เทส LIVE ครั้งแรก</option><option>รีรันเทส LIVE</option><option>LIVE ขายสินค้า</option></select></div><div><label>ระยะเวลา (นาที)</label><input type="number" min="0" name="minutes"></div><div><label>คนดู</label><input type="number" min="0" name="viewers"></div><div><label>ออเดอร์</label><input type="number" min="0" name="orders"></div><div><label>หมายเหตุ</label><input name="notes"></div><button class="primary">บันทึก LIVE</button></form></div><div class="panel"><h2>ประวัติ LIVE</h2>'+table(['วันที่','ช่อง','ประเภท','นาที','คนดู','ออเดอร์','หมายเหตุ'],state.live.slice().reverse().map(x=>['date','channel','type','minutes','viewers','orders','notes'].map(k=>escapeHtml(x[k]))))+'</div>'}
if(tab==='report'){h='<div class="panel"><h2>รายงานรวม 5 ช่อง</h2>'+table(['ช่อง','คลิป','วิว','ออเดอร์','ค่าคอม','ค่าโฆษณา'],[1,2,3,4,5].map(n=>{let a=state.logs.filter(x=>x.channel==='ช่อง '+n);return ['ช่อง '+n,...['clips','views','orders','commission','ads'].map(k=>a.reduce((s,x)=>s+Number(x[k]||0),0).toLocaleString())]}))+'<p><button id="export">ส่งออก CSV</button></p></div>'}
$('content').innerHTML=h;let day=$('workday');if(day)day.onchange=()=>{state.workday=day.value;save();render()};document.querySelectorAll('[data-day]').forEach(el=>el.onchange=()=>{state.done[el.dataset.day]=el.checked;save()});for(let [id,key] of [['logForm','logs'],['liveForm','live']]){let f=$(id);if(f){f.elements.date.value=new Date().toLocaleDateString('en-CA');f.onsubmit=e=>{e.preventDefault();state[key].push(Object.fromEntries(new FormData(f)));save();render()}}}let exp=$('export');if(exp)exp.onclick=()=>{let csv='date,channel,clips,views,orders,commission,ads\n'+state.logs.map(x=>['date','channel','clips','views','orders','commission','ads'].map(k=>JSON.stringify(x[k]||'')).join(',')).join('\n');let a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\uFEFF'+csv],{type:'text/csv'}));a.download='tiktok-report.csv';a.click();URL.revokeObjectURL(a.href)};save()}
document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>{tab=b.dataset.tab;render()}));render();
</script></body></html>`;
http.createServer((req,res)=>{if(req.url==='/health'){res.writeHead(200);res.end('ok');return}res.writeHead(200,{'content-type':'text/html; charset=utf-8'});res.end(html)}).listen(port,'0.0.0.0');